In [188]:
import os
import pandas as pd
import random
import numpy as np
train=pd.read_csv('data_train.csv',delimiter=",", index_col=None)
test=pd.read_csv('data_test.csv',delimiter=",",index_col=None)
train.head(2)
train["feature-1"]=train["feature-1"].replace(0.0,train['feature-1'].mean())
train["feature-2"]=train["feature-2"].replace(0.0,train['feature-2'].mean())
train["feature-3"]=train["feature-3"].replace(0.0,train['feature-3'].mean())
train["feature-4"]=train["feature-4"].replace(0.0,train['feature-4'].mean())
train["feature-5"]=train["feature-5"].replace(0.0,train['feature-5'].mean())
train["feature-6"]=train["feature-6"].replace(0.0,train['feature-6'].mean())
train["feature-7"]=train["feature-7"].replace(0.0,train['feature-7'].mean())
train["feature-8"]=train["feature-8"].replace(0.0,train['feature-8'].mean())
train["feature-9"]=train["feature-9"].replace(0.0,train['feature-9'].mean())
train["feature-10"]=train["feature-10"].replace(0.0,train['feature-10'].mean())

test["feature-1"]=test["feature-1"].replace(0.0,test['feature-1'].mean())
test["feature-2"]=test["feature-2"].replace(0.0,test['feature-2'].mean())
test["feature-3"]=test["feature-3"].replace(0.0,test['feature-3'].mean())
test["feature-4"]=test["feature-4"].replace(0.0,test['feature-4'].mean())
test["feature-5"]=test["feature-5"].replace(0.0,test['feature-5'].mean())
test["feature-6"]=test["feature-6"].replace(0.0,test['feature-6'].mean())
test["feature-7"]=test["feature-7"].replace(0.0,test['feature-7'].mean())
test["feature-8"]=test["feature-8"].replace(0.0,test['feature-8'].mean())
test["feature-9"]=test["feature-9"].replace(0.0,test['feature-9'].mean())
test["feature-10"]=test["feature-10"].replace(0.0,test['feature-10'].mean())



train["feature-1"]=(train["feature-1"]-train["feature-1"].min())/(train["feature-1"].max()-train["feature-1"].min())
train["feature-2"]=(train["feature-2"]-train["feature-2"].min())/(train["feature-2"].max()-train["feature-2"].min())
train["feature-3"]=(train["feature-3"]-train["feature-3"].min())/(train["feature-3"].max()-train["feature-3"].min())
train["feature-4"]=(train["feature-4"]-train["feature-4"].min())/(train["feature-4"].max()-train["feature-4"].min())
train["feature-5"]=(train["feature-5"]-train["feature-5"].min())/(train["feature-5"].max()-train["feature-5"].min())
train["feature-6"]=(train["feature-6"]-train["feature-6"].min())/(train["feature-6"].max()-train["feature-6"].min())
train["feature-7"]=(train["feature-7"]-train["feature-7"].min())/(train["feature-7"].max()-train["feature-7"].min())
train["feature-8"]=(train["feature-8"]-train["feature-8"].min())/(train["feature-8"].max()-train["feature-8"].min())
train["feature-9"]=(train["feature-9"]-train["feature-9"].min())/(train["feature-9"].max()-train["feature-9"].min())
train["feature-10"]=(train["feature-10"]-train["feature-10"].min())/(train["feature-10"].max()-train["feature-10"].min())

test["feature-10"]=(test["feature-10"]-test["feature-10"].min())/(test["feature-10"].max()-test["feature-10"].min())
test["feature-1"]=(test["feature-1"]-test["feature-1"].min())/(test["feature-1"].max()-test["feature-1"].min())
test["feature-2"]=(test["feature-2"]-test["feature-2"].min())/(test["feature-2"].max()-test["feature-2"].min())
test["feature-3"]=(test["feature-3"]-test["feature-3"].min())/(test["feature-3"].max()-test["feature-3"].min())
test["feature-4"]=(test["feature-4"]-test["feature-4"].min())/(test["feature-4"].max()-test["feature-4"].min())
test["feature-5"]=(test["feature-5"]-test["feature-5"].min())/(test["feature-5"].max()-test["feature-5"].min())
test["feature-6"]=(test["feature-6"]-test["feature-6"].min())/(test["feature-6"].max()-test["feature-6"].min())
test["feature-7"]=(test["feature-7"]-test["feature-7"].min())/(test["feature-7"].max()-test["feature-7"].min())
test["feature-8"]=(test["feature-8"]-test["feature-8"].min())/(test["feature-8"].max()-test["feature-8"].min())
test["feature-9"]=(test["feature-9"]-test["feature-9"].min())/(test["feature-9"].max()-test["feature-9"].min())

In [189]:
import keras
train_x=train.drop('label',axis=1)
train_y2 = train.label
#train_y = keras.utils.np_utils.to_categorical(train_y)
train_y=[]
for x in train_y2:
    train_y.append(x-1)
    


In [190]:
epochs = 40
batch_size = 64
import numpy
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.utils.np_utils import to_categorical
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
print(train_y)

[6, 2, 3, 2, 5, 3, 1, 5, 1, 2, 5, 1, 2, 1, 2, 0, 1, 1, 0, 0, 6, 1, 2, 2, 3, 6, 4, 2, 6, 2, 4, 5, 5, 2, 4, 6, 2, 4, 5, 2, 2, 2, 5, 5, 2, 2, 2, 4, 3, 6, 0, 3, 6, 1, 2, 1, 5, 0, 2, 2, 2, 5, 1, 2, 2, 2, 2, 6, 1, 0, 4, 0, 5, 2, 4, 0, 4, 2, 5, 6, 2, 5, 1, 1, 2, 1, 2, 2, 2, 2, 2, 0, 5, 3, 1, 2, 2, 1, 5, 3, 5, 6, 2, 2, 4, 2, 4, 0, 6, 1, 3, 0, 2, 2, 6, 6, 3, 3, 1, 2, 3, 4, 3, 2, 5, 3, 2, 5, 4, 2, 5, 2, 2, 6, 0, 5, 2, 1, 5, 2, 6, 2, 2, 4, 0, 2, 0, 1, 6, 0, 3, 2, 2, 1, 6, 5, 2, 0, 3, 4, 1, 4, 0, 5, 6, 2, 2, 1, 1, 3, 0, 1, 5, 1, 5, 6, 5, 1, 5, 2, 2, 1, 2, 2, 1, 5, 6, 2, 1, 1, 2, 0, 2, 2, 4, 5, 0, 2, 0, 2, 2, 3, 0, 6, 6, 3, 2, 0, 0, 4, 2, 0, 2, 4, 4, 1, 4, 2, 2, 4, 1, 4, 4, 0, 2, 3, 3, 3, 2, 1, 5, 0, 1, 2, 5, 1, 1, 1, 1, 1, 2, 5, 2, 2, 0, 1, 6, 3, 2, 0, 6, 5, 4, 0, 1, 0, 5, 4, 2, 2, 0, 2, 0, 0, 2, 2, 4, 1, 5, 6, 2, 0, 1, 0, 2, 4, 2, 6, 0, 1, 2, 1, 0, 5, 1, 0, 6, 2, 2, 2, 1, 1, 3, 0, 2, 0, 2, 2, 6, 2, 2, 0, 1, 1, 3, 0, 5, 0, 2, 1, 5, 1, 1, 4, 2, 5, 0, 2, 1, 2, 2, 1, 4, 2, 2, 1, 4, 1, 1, 6, 4, 2, 2, 

In [191]:
train_y = keras.utils.np_utils.to_categorical(train_y)
print(train_y)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [192]:

from keras.optimizers import SGD
model = Sequential()

model.add(Dense(300, activation='relu', input_dim=10))
model.add(Dropout(0.4))
model.add(Dense(164, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))


model.add(Dense(7, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(train_x, train_y,
          epochs=100,
          batch_size=128)


Epoch 1/100
6374/6374 [==============================] - 2s 238us/step - loss: 1.8628 - acc: 0.2841
Epoch 2/100
6374/6374 [==============================] - 0s 65us/step - loss: 1.8227 - acc: 0.3075
Epoch 3/100
6374/6374 [==============================] - 0s 72us/step - loss: 1.8099 - acc: 0.3081
Epoch 4/100
6374/6374 [==============================] - 0s 72us/step - loss: 1.7926 - acc: 0.3075
Epoch 5/100
6374/6374 [==============================] - 0s 78us/step - loss: 1.7726 - acc: 0.3091
Epoch 6/100
6374/6374 [==============================] - 0s 78us/step - loss: 1.7379 - acc: 0.3175
Epoch 7/100
6374/6374 [==============================] - 0s 77us/step - loss: 1.6811 - acc: 0.3549
Epoch 8/100
6374/6374 [==============================] - 0s 76us/step - loss: 1.6103 - acc: 0.4109
Epoch 9/100
6374/6374 [==============================] - 0s 66us/step - loss: 1.5108 - acc: 0.4470
Epoch 10/100
6374/6374 [==============================] - 0s 62us/step - loss: 1.4410 - acc: 0.4807
Epoch 11

6374/6374 [==============================] - 0s 64us/step - loss: 1.0612 - acc: 0.5977
Epoch 83/100
6374/6374 [==============================] - 0s 69us/step - loss: 1.0646 - acc: 0.5976
Epoch 84/100
6374/6374 [==============================] - 0s 59us/step - loss: 1.0660 - acc: 0.5971
Epoch 85/100
6374/6374 [==============================] - 0s 65us/step - loss: 1.0565 - acc: 0.6018
Epoch 86/100
6374/6374 [==============================] - 0s 68us/step - loss: 1.0550 - acc: 0.6009
Epoch 87/100
6374/6374 [==============================] - 0s 69us/step - loss: 1.0578 - acc: 0.6006
Epoch 88/100
6374/6374 [==============================] - 0s 59us/step - loss: 1.0504 - acc: 0.6017
Epoch 89/100
6374/6374 [==============================] - 0s 65us/step - loss: 1.0505 - acc: 0.6010
Epoch 90/100
6374/6374 [==============================] - 0s 64us/step - loss: 1.0385 - acc: 0.6024
Epoch 91/100
6374/6374 [==============================] - 0s 69us/step - loss: 1.0420 - acc: 0.5999
Epoch 92/100


In [196]:
pred = model.predict_classes(test)
pred=pred+1

In [197]:
pred.shape

(3000,)

In [198]:
pd.DataFrame(pred).to_csv('logistic1.csv',index=False,header=False)

(1000, 20)